version: 0.2

phases:
  install:
    commands:
      - echo "Start building ..."
  pre_build:
    commands:
      - echo "Build complete, prepare artifact"
  build:
    commands:
      - echo "Copying static files to output artifact..."
artifacts:
  files:
    - '**/*' 
  base-directory: '.'
  discard-paths: yes
  name: my-little-artifact
