version: 0.2

phases:
  install:
    commands:
      - echo "No special install commands for static website"
      - mkdir -p artifacts
  pre_build:
    commands:
      - echo "No pre-build steps for static website"
  build:
    commands:
      - echo "Copying static files to output artifact..."
      - ls -la
      - cp -r $(pwd)/* $(pwd)/artifacts/  
artifacts:
  files:
    - '**/*' 
  base-directory: 'artifacts' 
